name: Docker (Windows 2022)

on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [windows-2022]
        include:
        - os: windows-2022
          file: Dockerfile.windows
          tag: ltsc2022
          base: ltsc2022
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      run: |
        docker build . --pull --tag ${{ env.REGISTRY }}/${{ github.repository }}:${{ matrix.tag }} --build-arg BASE=${{ matrix.base }} --build-arg ARIAL_TTF_URL=${{ secrets.ARIAL_TTF_URL }}
      working-directory: windows2022
    - name: Push Docker image
      run: |
        docker push ${{ env.REGISTRY }}/${{ github.repository }}:${{ matrix.tag }}
      working-directory: windows2022
